---
title: "Check library"
author: "Jessica Chung /Melissa Carew"
date: "23/02/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
# read in records requiring correction in reference library
```{r}
asv_classif_ck <- read.csv('~/git/DNA_barcode_reference_database_construction/asv_classif_ck.csv', header = TRUE)

colnames(asv_classif_ck) <- c("asv_code", "kingdom", "phylum", "class", "order", "family", "genus", "species", "amplicon")
```

# Read in vsearch right amplicon
```{r}
right_vsearch <- read.table('~/git/metabarcoding_workflow/results/classification/preliminary/right_vsearch.tsv', header = TRUE, sep = "\t")

colnames(right_vsearch) <- c("asv_code", "id", "match", "length1", "length2", "X1", "X2", "X3", "X4", "X5", "X6", "X7")
```

# Read in vsearch short amplicon
```{r}
short_vsearch <- read.table('~/git/metabarcoding_workflow/results/classification/preliminary/short_vsearch.tsv', header = TRUE, sep = "\t")

colnames(short_vsearch) <- c("asv_code", "id", "match", "length1", "length2", "X1", "X2", "X3", "X4", "X5", "X6", "X7")
```

# isolate records with possible corrections needed
```{r}
short_ck <- merge(asv_classif_ck, short_vsearch, by = "asv_code", all.x = FALSE, all.y = FALSE)
```

# isolate records with possible corrections needed
```{r}
right_ck <- merge(asv_classif_ck, right_vsearch, by = "asv_code", all.x = FALSE, all.y = FALSE)
```


# isolate records with possible corrections needed
```{r}
short_rec_comp <- merge(short_ck, all_db, by = "id", all.x = FALSE, all.y = FALSE)

subset_short <- subset(short_rec_comp, match > 97)

#subset_short_cor <- subset(subset_short, species.x != species.y)

right_rec_comp <- merge(right_ck, all_db, by = "id", all.x = FALSE, all.y = FALSE)

subset_right <- subset(right_rec_comp, match > 97)

#subset_right_cor <- subset(subset_right, species.x != species.y)

```

```{r}
#rec_for_mod <- rbind(subset_short_cor, subset_right_cor)

rec_for_mod <- rbind(subset_short, subset_right)

rec_for_mod_unq <- rec_for_mod[!duplicated(rec_for_mod$id), ]


write.csv(rec_for_mod_unq, file = "~/git/DNA_barcode_reference_database_construction/updates_for_library_Feb_24.csv", row.names = FALSE)
```


